title: Akib Momin # your name (or website title) here
# the little icon that appears in the browser window's tab
favicon: ./favicon.ico
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  B.E. in Computer Science, Pune University
  <br><br>
  Software Engineer, Orion Technology Ltd
  <br><br>
  <a href="www.linkedin.com/in/akib001-momin">View My LinkedIn Profile</a> 
  <br><br>
  <a href="./pdf/Akib_Momin.pdf">View My CV</a> 

theme: jekyll-theme-minimal
google_analytics: G-CG33XZF49R # your Google Analytics tracking ID here
